export function exportToCSV(data, filename) {
  if (data.length === 0) return;

  const headers = Object.keys(data[0]);
  const csvContent = [
    headers.join(','),
    ...data.map(row => 
      headers.map(header => {
        const value = row[header];
        return typeof value === 'string' && value.includes(',') 
          ? `"${value}"` 
          : value;
      }).join(',')
    )
  ].join('\n');

  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);
  link.href = url;
  link.download = filename;
  link.click();
  URL.revokeObjectURL(url);
}

export function generateInventoryReport(inventory, products, branches, branchId = null) {
  let filteredInventory = inventory;
  if (branchId && branchId !== 'all') {
    filteredInventory = inventory.filter(item => item.branchId === branchId);
  }

  return filteredInventory.map(item => {
    const itemProductId = item.productId?._id || item.productId;
    const product = products.find(p => (p._id || p.id) === itemProductId);
    const branch = branches.find(b => b.id === item.branchId);
    return {
      Branch: branch?.name || '',
      Product: product?.name || '',
      Category: product?.category || '',
      'Current Stock': item.quantity,
      'Reorder Point': item.reorderPoint,
      'Stock Value': (product?.price || 0) * item.quantity,
      Status: item.quantity < item.reorderPoint ? 'Low' : 'Healthy',
      'Last Restock': item.lastRestock,
    };
  });
}

export function downloadPortfolioCSV(branchData, filename) {
  // Creating a visually separated CSV since PDF requires separate heavy libraries
  const rows = [];

  // Header Section
  rows.push(['StockSphere - Branch Inventory Report']);
  rows.push([]);
  rows.push(['Branch Name:', branchData.name]);
  rows.push(['Report Date:', new Date().toLocaleDateString()]);
  rows.push(['Branch Manager:', branchData.manager || 'Unassigned']);
  
  // Section separator
  rows.push([]);
  rows.push(['--- INVENTORY SUMMARY ---']);
  rows.push(['Total Products:', branchData.totalProducts]);
  rows.push(['Low Stock Items:', branchData.lowStock]);
  rows.push(['Total Inventory Value:', `₹${branchData.totalValue.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`]);
  
  rows.push([]);
  rows.push(['--- SALES SUMMARY ---']);
  rows.push(['Total Sales:', branchData.totalSales]);
  rows.push(['Revenue Generated:', `₹${branchData.revenue.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`]);

  rows.push([]);
  rows.push(['--- PRODUCT BREAKDOWN ---']);
  rows.push(['Product Name', 'Category', 'Quantity', 'Reorder Level', 'Status']);
  
  branchData.products.forEach(p => {
    rows.push([
      `"${p.name}"`, 
      p.category, 
      p.quantity, 
      p.reorderPoint, 
      p.quantity < p.reorderPoint ? 'LOW' : 'NORMAL'
    ]);
  });
  
  rows.push([]);
  rows.push(['Generated by StockSphere Analytics']);

  const csvContent = rows.map(r => r.join(',')).join('\n');
  
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);
  link.href = url;
  link.download = filename;
  link.click();
  URL.revokeObjectURL(url);
}

